# Generated by Django 5.2.1 on 2025-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpret',
            name='popis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interpret',
            name='rok_vzniku',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpret',
            name='zeme_puvodu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='zanr',
            name='popis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zanr',
            name='popularita',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
