# Generated by Django 5.2.1 on 2025-06-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='pocet_skladeb',
            new_name='rok',
        ),
        migrations.RemoveField(
            model_name='album',
            name='rok_vydani',
        ),
        migrations.RemoveField(
            model_name='interpret',
            name='popis',
        ),
        migrations.RemoveField(
            model_name='interpret',
            name='zanr',
        ),
        migrations.AddField(
            model_name='album',
            name='zanr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muzika.zanr'),
        ),
    ]
