# Generated by Django 5.2.1 on 2025-06-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_interpret_popis_interpret_rok_vzniku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='rok',
            new_name='rok_vydanni',
        ),
        migrations.RenameField(
            model_name='interpret',
            old_name='rok_vzniku',
            new_name='narozeni',
        ),
    ]
