# Generated by Django 5.2.1 on 2025-06-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_rename_rok_album_rok_vydanni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='alba/'),
        ),
        migrations.AddField(
            model_name='interpret',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='interpreti/'),
        ),
    ]
